name: Java CI with Gradle

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - main  # Run the tests on push to the main branch
  pull_request:
    branches:
      - main  # Run the tests on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The GitHub Actions runner environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up JDK 11 (or any Java version you need)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # JDK distribution (Temurin is commonly used)
        java-version: '11'

    # Step 3: Grant execute permission for Gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Build the project using Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Run the tests using Gradle
    - name: Run tests with Gradle
      run: ./gradlew test
