name: Java CI without Gradle Wrapper

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Use Temurin distribution for JDK
        java-version: '11'

    - name: Install Gradle
      run: sudo apt-get install gradle -y  # Installs the latest available Gradle version

    - name: Verify Gradle version
      run: gradle -v  # Verifies the installed Gradle version

    - name: Build with Gradle
      run: gradle build  # Runs the build command directly

    - name: Run tests with Gradle
      run: gradle test  # Runs the tests directly
